# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '品牌', 'verbose_name_plural': '品牌'},
        ),
        migrations.RemoveField(
            model_name='goodscategorybrand',
            name='imgae',
        ),
        migrations.AddField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table='goods_goodsbrand',
        ),
    ]
